# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml

name: germs

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::r-base=4.1.3
  - conda-forge::r-devtools=2.4.4
  - conda-forge::r-data.table=1.14.2
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-optparse=1.7.3
  - conda-forge::r-scales=1.2.0
  - conda-forge::r-ggthemes=4.2.4
  - conda-forge::r-cowplot=1.1.1
  - conda-forge::r-patchwork=1.1.1
  - conda-forge::r-logger=0.2.2
  - bioconda::bioconductor-biostrings=2.62.0