# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates sliding mean
#'
#' @param iv numeric vector
#' @param ws window size
#'
#' @return numeric vector of sliding means
calculate_sliding_mean <- function(iv, ws) {
    .Call(`_germs_calculate_sliding_mean`, iv, ws)
}

#' Chops sequence into k-mers
#'
#' @param input_seq A character string
#' @param k_len an integer specifying the length of the k-mer
#'
#' @return character vector of k-mers
kmer_chopper <- function(input_seq, k_len) {
    .Call(`_germs_kmer_chopper`, input_seq, k_len)
}

#' Get list of k-mer multivalencies
#'
#' @param ins list of ??
#' @param k_len an integer specifying the length of the k-mer
#' @param window_size integer specifying window_size
#' @param hamming_distances the Hamming distance matrix
#' @param positional_distances the positional distance vector
#'
#' @return a list of k-mer multivalencies
list_kmer_multivalencies <- function(ins, k_len, window_size, hamming_distances, positional_distances) {
    .Call(`_germs_list_kmer_multivalencies`, ins, k_len, window_size, hamming_distances, positional_distances)
}

rcpp_hello <- function() {
    .Call(`_germs_rcpp_hello`)
}

