# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Chops sequence into k-mers
#'
#' @param input_seq A character string
#' @param k_len an integer specifying the length of the k-mer
#'
#' @return character vector of k-mers
kmer_chopper <- function(input_seq, k_len) {
    .Call(`_germs_kmer_chopper`, input_seq, k_len)
}

rcpp_hello <- function() {
    .Call(`_germs_rcpp_hello`)
}

