# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Chops sequence into k-mers
#'
#' @param input_seq a character string
#' @param k_len an integer specifying the length of the k-mer
#'
#' @return character vector of k-mers
kmer_chopper <- function(input_seq, k_len) {
    .Call(`_germs_kmer_chopper`, input_seq, k_len)
}

#' Calculates k-mer multivalencies
#'
#' @param input_seq sequence string
#' @param k_len an integer specifying the length of the k-mer
#' @param window_size integer specifying window_size
#' @param hamming_distances the Hamming distance matrix
#' @param positional_distances the positional distance vector
#'
#' @return a vector of k-mer multivalencies
calculate_kmer_multivalencies <- function(input_seq, k_len, window_size, hamming_distances, positional_distances) {
    .Call(`_germs_calculate_kmer_multivalencies`, input_seq, k_len, window_size, hamming_distances, positional_distances)
}

#' Get list of k-mer multivalencies
#'
#' @param ins list of ??
#' @param k_len an integer specifying the length of the k-mer
#' @param window_size integer specifying window_size
#' @param hamming_distances the Hamming distance matrix
#' @param positional_distances the positional distance vector
#'
#' @return a list of k-mer multivalencies
list_kmer_multivalencies <- function(ins, k_len, window_size, hamming_distances, positional_distances) {
    .Call(`_germs_list_kmer_multivalencies`, ins, k_len, window_size, hamming_distances, positional_distances)
}

#' Creates a list of sliding means.
#'
#' @param ins A list of numeric vectors (intended to be from  thelist_kmer_multivalencies function).
#' @param window_size An integer specifying the size of the window within which to calculate mean values.
#'
#' @return list of numeric vectors containing the sliding window mean values.
NULL

#' Calculates sliding mean
#'
#' @param iv numeric vector
#' @param ws window size
#'
#' @return numeric vector of sliding means
calculate_sliding_mean <- function(iv, ws) {
    .Call(`_germs_calculate_sliding_mean`, iv, ws)
}

list_sliding_means <- function(ins, window_size) {
    .Call(`_germs_list_sliding_means`, ins, window_size)
}

